name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1'
          - 'lts'
          - 'pre'
        os:
          - ubuntu-latest
          - windows-latest
    uses: "SciML/.github/.github/workflows/tests.yml@v1"
    with:
      julia-version: "${{ matrix.version }}"
      julia-arch: "x64"
      os: "${{ matrix.os }}"
    secrets: "inherit"
  docs:
    name: Documentation
    uses: "SciML/.github/.github/workflows/documentation.yml@v1"
    with:
      coverage: false
    secrets: "inherit"
