name: CI
on:
  - push
  - pull_request
jobs:
  tests:
    uses: "SciML/.github/.github/workflows/grouped-tests.yml@v1"
    with:
      coverage-directories: "src"
    secrets: "inherit"
  docs:
    name: Documentation
    uses: "SciML/.github/.github/workflows/documentation.yml@v1"
    with:
      coverage: false
    secrets: "inherit"
