name: IntegrationTest
on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:

jobs:
  test:
    name: ${{ matrix.package.repo }}/${{ matrix.package.group }}/${{ matrix.julia-version }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: [1]
        package:
          - {user: JuliaArrays, repo: ArrayInterface.jl, group: ArrayInterface}
          - {user: JuliaSIMD, repo: VectorizationBase.jl, group: Interface}
          - {user: JuliaSIMD, repo: LoopVectorization.jl, group: Downstream3}
          - {user: JuliaDiff, repo: SparseDiffTools.jl, group: Core}
          - {user: SciML, repo: SciMLBase.jl, group: Core}
          - {user: SciML, repo: DiffEqBase.jl, group: Core}
          - {user: SciML, repo: DiffEqBase.jl, group: Downstream}
          - {user: SciML, repo: DiffEqBase.jl, group: Downstream2}
          - {user: SciML, repo: DiffEqSensitivity.jl, group: Core}
          - {user: SciML, repo: OrdinaryDiffEq.jl, group: Core}
          - {user: SciML, repo: OrdinaryDiffEq.jl, group: Interface}
          - {user: SciML, repo: DelayDiffEq.jl, group: Interface}
    uses: "SciML/.github/.github/workflows/downstream.yml@v1"
    with:
      julia-version: "${{ matrix.julia-version }}"
      julia-arch: "x64"
      owner: "${{ matrix.package.user }}"
      repo: "${{ matrix.package.repo }}"
      group: "${{ matrix.package.group }}"
    secrets: "inherit"
